### PR TITLE
[Translation 4.26] Progressive Delivery with Jenkins X

### PR DESCRIPTION
**Pull request by donhui**
### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://blog.csanchez.org/2019/01/24/progressive-delivery-with-jenkins-x/)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [x] [微信公众号](https://github.com/linuxsuren)
- [x] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [x] [简书](https://github.com/yJunS)
- [x] [掘金](https://github.com/zacker330)

### CODE REVIEW

**Review by LinuxSuRen — APPROVED** [review]
LGTM

**Comment by zacker330** [comment]
LGTM

**Comment by donhui** [comment]
开源中国：
https://my.oschina.net/jenkinszh/blog/3042777

**Comment by zacker330** [comment]
* 简书：https://www.jianshu.com/p/eea974f3f8b8
* 掘金：https://juejin.im/post/5cc43a4a6fb9a03239689248

**Comment by zacker330** [comment]
* 简书：https://www.jianshu.com/p/eea974f3f8b8
* 掘金：https://juejin.im/post/5cc43a4a6fb9a03239689248

**Pull request merged**
